export const actionTypes = {
  // Product List
  PRODUCT_LIST_REQUEST: "PRODUCT_LIST_REQUEST",
  PRODUCT_LIST_SUCCESS: "PRODUCT_LIST_SUCCESS",
  PRODUCT_LIST_FAIL: "PRODUCT_LIST_FAIL",

  // Product Details
  PRODUCT_DETAILS_REQUEST: "PRODUCT_DETAILS_REQUEST",
  PRODUCT_DETAILS_SUCCESS: "PRODUCT_DETAILS_SUCCESS",
  PRODUCT_DETAILS_FAIL: "PRODUCT_DETAILS_FAIL",

  // Cart
  CART_ADD_ITEM: "CART_ADD_ITEM",
  CART_REMOVE_ITEM: "CART_REMOVE_ITEM",

  // User Login
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",

  // User Logout
  USER_LOGOUT: "USER_LOGOUT",

  // User Register
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAIL: "USER_REGISTER_FAIL",

  // User Details
  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAIL: "USER_DETAILS_FAIL",
  USER_DETAILS_RESET: "USER_DETAILS_RESET",

  // User Update
  USER_UPDATE_PROFILE_REQUEST: "USER_UPDATE_PROFILE_REQUEST",
  USER_UPDATE_PROFILE_SUCCESS: "USER_UPDATE_PROFILE_SUCCESS",
  USER_UPDATE_PROFILE_FAIL: "USER_UPDATE_PROFILE_FAIL",
  USER_UPDATE_PROFILE_RESET: "USER_UPDATE_PROFILE_RESET",

  // Shipping Address
  CART_SAVE_SHIPPING_ADDRESS: "CART_SAVE_SHIPPING_ADDRESS",

  // Payment Method
  CART_SAVE_PAYMENT_METHOD: "CART_SAVE_PAYMENT_METHOD",

  // Clear Cart
  CART_CLEAR_ITEMS: "CART_CLEAR_ITEMS",

  // Order
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAIL: "ORDER_CREATE_FAIL",
  ORDER_CREATE_RESET: "ORDER_CREATE_RESET",

  // Order Details By Id
  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAIL: "ORDER_DETAILS_FAIL",

  // Order pay
  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAIL: "ORDER_PAY_FAIL",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",

  // All Order Lists
  ORDER_LIST_MY_REQUEST: "ORDER_LIST_MY_REQUEST",
  ORDER_LIST_MY_SUCCESS: "ORDER_LIST_MY_SUCCESS",
  ORDER_LIST_MY_FAIL: "ORDER_LIST_MY_FAIL",
  ORDER_LIST_MY_RESET: "ORDER_LIST_MY_RESET",

  // ========= Admin ===============
  // @admin
  // User List
  USER_LIST_REQUEST: "USER_LIST_REQUEST",
  USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
  USER_LIST_FAIL: "USER_LIST_FAIL",
  USER_LIST_RESET: "USER_LIST_RESET",

  // @admin
  // Delete User
  USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_DELETE_FAIL: "USER_DELETE_FAIL",

  // @admin
  // Update User
  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAIL: "USER_UPDATE_FAIL",
  USER_UPDATE_RESET: "USER_UPDATE_RESET",

  // @admin
  // Product Delete
  PRODUCT_DELETE_REQUEST: "PRODUCT_DELETE_REQUEST",
  PRODUCT_DELETE_SUCCESS: "PRODUCT_DELETE_SUCCESS",
  PRODUCT_DELETE_FAIL: "PRODUCT_DELETE_FAIL",

  // @admin
  // Product Create
  PRODUCT_CREATE_REQUEST: "PRODUCT_CREATE_REQUEST",
  PRODUCT_CREATE_SUCCESS: "PRODUCT_CREATE_SUCCESS",
  PRODUCT_CREATE_FAIL: "PRODUCT_CREATE_FAIL",
  PRODUCT_CREATE_RESET: "PRODUCT_CREATE_RESET",

  // @admin
  // Product Update
  PRODUCT_UPDATE_REQUEST: "PRODUCT_UPDATE_REQUEST",
  PRODUCT_UPDATE_SUCCESS: "PRODUCT_UPDATE_SUCCESS",
  PRODUCT_UPDATE_FAIL: "PRODUCT_UPDATE_FAIL",
  PRODUCT_UPDATE_RESET: "PRODUCT_UPDATE_RESET",

  // @admin
  // All Orders
  ORDER_LIST_REQUEST: "ORDER_LIST_REQUEST",
  ORDER_LIST_SUCCESS: "ORDER_LIST_SUCCESS",
  ORDER_LIST_FAIL: "ORDER_LIST_FAIL",
};
